//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHBack.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIGRHBack.Ressources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le profil a été activé avec succès..
        /// </summary>
        public static string ActiverSuccess {
            get {
                return ResourceManager.GetString("ActiverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur a été activé avec succès..
        /// </summary>
        public static string ActiverUserSuccess {
            get {
                return ResourceManager.GetString("ActiverUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte d&apos;utilisateur activé avec succès..
        /// </summary>
        public static string ActiveUserSuccess {
            get {
                return ResourceManager.GetString("ActiveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de l&apos;ajout..
        /// </summary>
        public static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ajout ou la modification du grade a échoué.
        /// </summary>
        public static string AddOrUpdateFailedGrade {
            get {
                return ResourceManager.GetString("AddOrUpdateFailedGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ajout ou la modification du grade a été effectué avec succès.
        /// </summary>
        public static string AddOrUpdateSuccessGrade {
            get {
                return ResourceManager.GetString("AddOrUpdateSuccessGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout effectué avec succès..
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assignation de role {0} avec succès..
        /// </summary>
        public static string AssignRoleSuccess {
            get {
                return ResourceManager.GetString("AssignRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de l&apos;utilisateur avec succès.
        /// </summary>
        public static string CreatedUserSuccess {
            get {
                return ResourceManager.GetString("CreatedUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression du role à {0} avec succès..
        /// </summary>
        public static string DeleteRoleSuccess {
            get {
                return ResourceManager.GetString("DeleteRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le profil a été désactivé avec succès..
        /// </summary>
        public static string DesactiverSuccess {
            get {
                return ResourceManager.GetString("DesactiverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur a été désactivé avec succès..
        /// </summary>
        public static string DesactiverUserSuccess {
            get {
                return ResourceManager.GetString("DesactiverUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce compte d&apos;utilisateur a été desactivé avec succès..
        /// </summary>
        public static string DesactiveUserSuccess {
            get {
                return ResourceManager.GetString("DesactiveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette adresse electronique {0} est déjà utilisée..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification de l&apos;utilisateur avec succès..
        /// </summary>
        public static string EditedUserSuccess {
            get {
                return ResourceManager.GetString("EditedUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;activation du compte d&apos;utilisateur..
        /// </summary>
        public static string ErrorActiveUser {
            get {
                return ResourceManager.GetString("ErrorActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;ajout de la photo..
        /// </summary>
        public static string ErrorAddedPhoto {
            get {
                return ResourceManager.GetString("ErrorAddedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur Assignation de role..
        /// </summary>
        public static string ErrorAssignRole {
            get {
                return ResourceManager.GetString("ErrorAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur Assignation de role, utilisateur introuvable..
        /// </summary>
        public static string ErrorAssignRoleUserNotFound {
            get {
                return ResourceManager.GetString("ErrorAssignRoleUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce numero de cni existe déjà dans le système..
        /// </summary>
        public static string ErrorCniExist {
            get {
                return ResourceManager.GetString("ErrorCniExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de création de la fiche personnel..
        /// </summary>
        public static string ErrorCreateFiche {
            get {
                return ResourceManager.GetString("ErrorCreateFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de création de l&apos;utilisateur..
        /// </summary>
        public static string ErrorCreationUser {
            get {
                return ResourceManager.GetString("ErrorCreationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur suppression de role, utilisateur introuvable.
        /// </summary>
        public static string ErrorDeleteRoleUser {
            get {
                return ResourceManager.GetString("ErrorDeleteRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de désactivation du compte d&apos;utilisateur..
        /// </summary>
        public static string ErrorDesactiveUser {
            get {
                return ResourceManager.GetString("ErrorDesactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet identitiant {0} existe deja dans le système..
        /// </summary>
        public static string ErrorDuplicateUserName {
            get {
                return ResourceManager.GetString("ErrorDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de modification de l&apos;utilisateur..
        /// </summary>
        public static string ErrorEditedUser {
            get {
                return ResourceManager.GetString("ErrorEditedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de modification de l&apos;utilisateur ! Introuvable..
        /// </summary>
        public static string ErrorEditedUserNotFound {
            get {
                return ResourceManager.GetString("ErrorEditedUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette adresse electronique existe déjà dans le système..
        /// </summary>
        public static string ErrorEmailExist {
            get {
                return ResourceManager.GetString("ErrorEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce type de fichier n&apos;est pas autorisé dans le système..
        /// </summary>
        public static string ErrorextensionFile {
            get {
                return ResourceManager.GetString("ErrorextensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre fichier est trop grand..
        /// </summary>
        public static string ErrorFileLarge {
            get {
                return ResourceManager.GetString("ErrorFileLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de reinitialisation de mot de passe..
        /// </summary>
        public static string ErrorForgotPassword {
            get {
                return ResourceManager.GetString("ErrorForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de réinitialisation de mot de passe..
        /// </summary>
        public static string ErrorForgotPasswordNotFound {
            get {
                return ResourceManager.GetString("ErrorForgotPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de récupération de l&apos;élément avec succès..
        /// </summary>
        public static string ErrorGetOneUser {
            get {
                return ResourceManager.GetString("ErrorGetOneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur interne est survenue..
        /// </summary>
        public static string ErrorInternal500 {
            get {
                return ResourceManager.GetString("ErrorInternal500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocage : Trop de tentatives de connexion. Réessayez plus tard..
        /// </summary>
        public static string ErrorLoginFailedCount {
            get {
                return ResourceManager.GetString("ErrorLoginFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant ou mot de passe incorrect..
        /// </summary>
        public static string ErrorLoginIdentity {
            get {
                return ResourceManager.GetString("ErrorLoginIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre compte est suspendu. Veuillez contacter le service support..
        /// </summary>
        public static string ErrorLoginSuspended {
            get {
                return ResourceManager.GetString("ErrorLoginSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette matricule existe déjà dans le système..
        /// </summary>
        public static string ErrorMatriculeExist {
            get {
                return ResourceManager.GetString("ErrorMatriculeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez joindre une photo dans la fiche personnelle..
        /// </summary>
        public static string ErrorPhotoRequired {
            get {
                return ResourceManager.GetString("ErrorPhotoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de reinitialisation de votre mot de passe..
        /// </summary>
        public static string ErrorResetPassword {
            get {
                return ResourceManager.GetString("ErrorResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de reinitialisation de votre mot de passe. L&apos;utilisateur est introuvable..
        /// </summary>
        public static string ErrorResetPasswordUserNotFound {
            get {
                return ResourceManager.GetString("ErrorResetPasswordUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce numéro de téléphone existe déjà dans le système..
        /// </summary>
        public static string ErrorTelephoneExist {
            get {
                return ResourceManager.GetString("ErrorTelephoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de révoquation de mot de passe..
        /// </summary>
        public static string ErrorTokenRevoke {
            get {
                return ResourceManager.GetString("ErrorTokenRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec mise à jour acte.
        /// </summary>
        public static string ErrorUpdateActe {
            get {
                return ResourceManager.GetString("ErrorUpdateActe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de modification de la photo..
        /// </summary>
        public static string ErrorUpdatedSignaturePhoto {
            get {
                return ResourceManager.GetString("ErrorUpdatedSignaturePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de modification de la fiche de personnel..
        /// </summary>
        public static string ErrorUpdateFiche {
            get {
                return ResourceManager.GetString("ErrorUpdateFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de validation de la fiche de personnel..
        /// </summary>
        public static string ErrorValidateFiche {
            get {
                return ResourceManager.GetString("ErrorValidateFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un e-mail de réinitialisation a été envoyé à votre adresse. Suivez les intructions fournies pour réinitialiser votre mot de passe..
        /// </summary>
        public static string ForgotPasswordSuccess {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la récupération des actes de gestion..
        /// </summary>
        public static string GetAllActesGestionError {
            get {
                return ResourceManager.GetString("GetAllActesGestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actes de gestion récupérés avec succès..
        /// </summary>
        public static string GetAllActesGestionSuccess {
            get {
                return ResourceManager.GetString("GetAllActesGestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de la récupuration de la liste..
        /// </summary>
        public static string GetAllError {
            get {
                return ResourceManager.GetString("GetAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des grades obtenu avec succès.
        /// </summary>
        public static string GetAllGrade {
            get {
                return ResourceManager.GetString("GetAllGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des profils..
        /// </summary>
        public static string GetAllProfil {
            get {
                return ResourceManager.GetString("GetAllProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste récupérée avec succès..
        /// </summary>
        public static string GetAllSuccess {
            get {
                return ResourceManager.GetString("GetAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récupération des données avec succès..
        /// </summary>
        public static string GetDatasSuccess {
            get {
                return ResourceManager.GetString("GetDatasSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de la récupération de l&apos;élément..
        /// </summary>
        public static string GetError {
            get {
                return ResourceManager.GetString("GetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grade obtenu avec succès.
        /// </summary>
        public static string GetOneGrade {
            get {
                return ResourceManager.GetString("GetOneGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récupération de l&apos;élément avec succès..
        /// </summary>
        public static string GetOneUserSuccess {
            get {
                return ResourceManager.GetString("GetOneUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récupération effectué avec succès..
        /// </summary>
        public static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le grade n&apos;existe pas dans le système.
        /// </summary>
        public static string GradeNotFound {
            get {
                return ResourceManager.GetString("GradeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre token est invalide..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet identifiant {0} est invalide..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion utilisateur avec succès..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de l&apos;activation ou de la désactivition..
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe est incorrect..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe doit comporter au moins un chiffre (0-9)..
        /// </summary>
        public static string PasswordRequireDigits {
            get {
                return ResourceManager.GetString("PasswordRequireDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe doit comporter au moins une lettre majuscule(a-z)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe doit comporter au moins un caractère non alphanumérique..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe doit comporter au moins une lettre majuscule(A-Z)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe a été changé avec succès. Veuillez vous connecter, s&apos;il vous plaît..
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiche de personnel créée avec succès..
        /// </summary>
        public static string SuccessCreateFiche {
            get {
                return ResourceManager.GetString("SuccessCreateFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification de la fiche personnel avec succès..
        /// </summary>
        public static string SuccessUpdateFiche {
            get {
                return ResourceManager.GetString("SuccessUpdateFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiche de personnel validée avec succès..
        /// </summary>
        public static string SuccessValidateFiche {
            get {
                return ResourceManager.GetString("SuccessValidateFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre token a été rafraichi avec succès..
        /// </summary>
        public static string TokenRefreshSuccess {
            get {
                return ResourceManager.GetString("TokenRefreshSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre token a été révoqué avec succès..
        /// </summary>
        public static string TokenRevokeSuccess {
            get {
                return ResourceManager.GetString("TokenRevokeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de revoquation de token. Utilisateur introuvable..
        /// </summary>
        public static string TokenRevokeUserNotFound {
            get {
                return ResourceManager.GetString("TokenRevokeUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour acte effectuée avec succes.
        /// </summary>
        public static string UpdateActeSuccess {
            get {
                return ResourceManager.GetString("UpdateActeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de mise à jour..
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification mot de passe avec succès..
        /// </summary>
        public static string UpdatePasswordSuccess {
            get {
                return ResourceManager.GetString("UpdatePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour effectuée..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de révocation du profil ({0}) à un utilisateur ou le profil est inactif..
        /// </summary>
        public static string UserRoleNot {
            get {
                return ResourceManager.GetString("UserRoleNot", resourceCulture);
            }
        }
    }
}
