//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:SIGRHMetier/Model/C__EFMigrationsHistory.cs
    public partial class C__EFMigrationsHistory
========
    public partial class TD_Signature_Photo
>>>>>>>> 57e844a1db0e93e4763f494293ced1ef1bf8fb90:SIGRHMetier/Model/TD_Signature_Photo.cs
    {
        public string MigrationId { get; set; }
        public string ProductVersion { get; set; }
    }
}
