//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdJUSTICEEntities : DbContext
    {
        public BdJUSTICEEntities()
            : base("name=BdJUSTICEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TD_ActeAdminstration> TD_ActeAdminstration { get; set; }
        public virtual DbSet<TD_ActeGestion> TD_ActeGestion { get; set; }
        public virtual DbSet<TD_FichePersonnelJudiciaire> TD_FichePersonnelJudiciaire { get; set; }
        public virtual DbSet<TD_Fichier> TD_Fichier { get; set; }
        public virtual DbSet<TD_LogErreur> TD_LogErreur { get; set; }
        public virtual DbSet<TD_MenuItem> TD_MenuItem { get; set; }
        public virtual DbSet<TD_SousMenu> TD_SousMenu { get; set; }
        public virtual DbSet<TD_TokenInfo> TD_TokenInfo { get; set; }
        public virtual DbSet<TD_Utilisateur> TD_Utilisateur { get; set; }
        public virtual DbSet<TP_ClasseJuridiction> TP_ClasseJuridiction { get; set; }
        public virtual DbSet<TP_Commune> TP_Commune { get; set; }
        public virtual DbSet<TP_CorpsJudiciaire> TP_CorpsJudiciaire { get; set; }
        public virtual DbSet<TP_Departement> TP_Departement { get; set; }
        public virtual DbSet<TP_Echelon> TP_Echelon { get; set; }
        public virtual DbSet<TP_EmploiJudiciaire> TP_EmploiJudiciaire { get; set; }
        public virtual DbSet<TP_Fonction> TP_Fonction { get; set; }
        public virtual DbSet<TP_GradeFonctionnaireJustice> TP_GradeFonctionnaireJustice { get; set; }
        public virtual DbSet<TP_GradeMagistrat> TP_GradeMagistrat { get; set; }
        public virtual DbSet<TP_Groupe> TP_Groupe { get; set; }
        public virtual DbSet<TP_Indice> TP_Indice { get; set; }
        public virtual DbSet<TP_Juridiction> TP_Juridiction { get; set; }
        public virtual DbSet<TP_ModePassage> TP_ModePassage { get; set; }
        public virtual DbSet<TP_NatureDecision> TP_NatureDecision { get; set; }
        public virtual DbSet<TP_Profil> TP_Profil { get; set; }
        public virtual DbSet<TP_Quartier> TP_Quartier { get; set; }
        public virtual DbSet<TP_Region> TP_Region { get; set; }
        public virtual DbSet<TP_TypeActe> TP_TypeActe { get; set; }
        public virtual DbSet<TP_TypeDocument> TP_TypeDocument { get; set; }
        public virtual DbSet<TP_TypeJuridiction> TP_TypeJuridiction { get; set; }
        public virtual DbSet<TP_TypePersonnel> TP_TypePersonnel { get; set; }
        public virtual DbSet<TR_CompositionJuridiction> TR_CompositionJuridiction { get; set; }
        public virtual DbSet<TR_RessortJuridictionDepartement> TR_RessortJuridictionDepartement { get; set; }
        public virtual DbSet<TR_RessortJuridictionRegion> TR_RessortJuridictionRegion { get; set; }
        public virtual DbSet<TD_Signature_Photo> TD_Signature_Photo { get; set; }
        public virtual DbSet<TP_FonctionFonctionnaireJustice> TP_FonctionFonctionnaireJustice { get; set; }
    }
}
