//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Acte1
    {
        public int Act_Id { get; set; }
        public string Act_NumeroDecision { get; set; }
        public Nullable<System.DateTime> Act_DateCreation { get; set; }
        public string Act_Nad_Code { get; set; }
        public Nullable<int> Act_EstValide { get; set; }
        public Nullable<System.DateTime> Act_DateValidation { get; set; }
        public Nullable<System.DateTime> Act_DateSoumission { get; set; }
        public Nullable<System.DateTime> Act_DateModification { get; set; }
        public string Act_TyD_Code { get; set; }
        public Nullable<int> Act_Fic_Id { get; set; }
        public Nullable<int> Act_FPJ_Id { get; set; }
        public Nullable<int> Act_UtiCreation_Id { get; set; }
        public Nullable<int> Act_UtiValidation_Id { get; set; }
    }
}
