//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ActeAdminstration
    {
        public int Ata_Id { get; set; }
        public string Ata_Residence { get; set; }
        public string Ata_Ech_Code { get; set; }
        public string Ata_Emp_Code { get; set; }
        public string Ata_Fon_Code { get; set; }
        public string Ata_Jur_Emp_Code { get; set; }
        public string Ata_Jur_Fon_Code { get; set; }
        public string Ata_NumeroDecision { get; set; }
        public Nullable<System.DateTime> Ata_DateCreation { get; set; }
        public string Ata_Nad_Code { get; set; }
        public Nullable<int> Ata_EstValide { get; set; }
        public Nullable<System.DateTime> Ata_DateValidation { get; set; }
        public Nullable<System.DateTime> Ata_DateSoumission { get; set; }
        public Nullable<System.DateTime> Ata_DateModification { get; set; }
        public string Ata_TyD_Code { get; set; }
        public Nullable<int> Ata_Fic_Id { get; set; }
        public Nullable<int> Ata_FPJ_Id { get; set; }
        public Nullable<int> Ata_UtiCreation_Id { get; set; }
        public Nullable<int> Ata_UtiValidation_Id { get; set; }
        public string Ata_Gro_Code { get; set; }
        public string Ata_Grm_Code { get; set; }
        public string Ata_Grf_Code { get; set; }
        public string Ata_Cju_Code { get; set; }
        public Nullable<long> Ata_Ind_Valeur { get; set; }
    }
}
