//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ActeGestion
    {
        public int Atg_Id { get; set; }
        public Nullable<System.DateTime> Atg_DateCreation { get; set; }
        public Nullable<System.DateTime> Atg_DateEntreeVigueur { get; set; }
        public string Atg_Nad_Code { get; set; }
        public string Atg_NumeroDecision { get; set; }
        public Nullable<int> Atg_EstValide { get; set; }
        public Nullable<System.DateTime> Atg_DateValidation { get; set; }
        public Nullable<System.DateTime> Atg_DateSoumission { get; set; }
        public Nullable<System.DateTime> Atg_DateModification { get; set; }
        public string Atg_TyD_Code { get; set; }
        public Nullable<int> Atg_Fic_Id { get; set; }
        public Nullable<int> Atg_FPJ_Id { get; set; }
        public Nullable<int> Atg_UtiCreation_Id { get; set; }
        public Nullable<int> Atg_UtiValidation_Id { get; set; }
    }
}
