//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Fichier
    {
        public int Fic_Id { get; set; }
        public string Fic_Chemin { get; set; }
        public string Fic_Type { get; set; }
        public Nullable<System.DateTime> Fic_DateCreation { get; set; }
        public byte[] Fic_Photo { get; set; }
    }
}
