//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_LogErreur
    {
        public int Log_Id { get; set; }
        public string Log_Page { get; set; }
        public string Log_Fonction { get; set; }
        public Nullable<System.DateTime> Log_DateErreur { get; set; }
        public string Log_Erreur { get; set; }
    }
}
