//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;

    public partial class TD_Signature_Photo
    {
        public int SIP_Id { get; set; }
        public string SIP_Name { get; set; }
        public string SIP_contentype { get; set; }
        public byte[] SIP_FileSave { get; set; }
    }
}
