//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Utilisateur
    {
        public int Uti_Id { get; set; }
        public string Uti_Login { get; set; }
        public string Uti_Nom { get; set; }
        public string Uti_Prenom { get; set; }
        public string Uti_Pro_Code { get; set; }
        public string Uti_ActifOuiNon { get; set; }
        public Nullable<System.DateTime> Uti_DateCreation { get; set; }
        public string Uti_Poste { get; set; }
        public string Uti_Telephone { get; set; }
        public string Uti_Email { get; set; }
        public string Uti_Adresse { get; set; }
        public string Uti_NewConnection { get; set; }
        public string Uti_idUser { get; set; }
    }
}
