//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_NiveauCarriere1
    {
        public int Niv_Id { get; set; }
        public int Niv_Gra_Id { get; set; }
        public int Niv_Ech_Id { get; set; }
        public int Niv_Gro_Id { get; set; }
        public int Niv_Ind_Id { get; set; }
        public int Niv_MoP_ModePassage { get; set; }
        public int Niv_DureePassage { get; set; }
        public string Niv_Code { get; set; }
    }
}
