//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_Profil
    {
        public int Pro_Id { get; set; }
        public string Pro_Libelle { get; set; }
        public string Pro_ActifOuiNon { get; set; }
        public string Pro_Code { get; set; }
    }
}
