//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_TypeJuridiction
    {
        public int TyJ_Id { get; set; }
        public string TyJ_Libelle { get; set; }
        public string TyJ_LibelleAnc { get; set; }
        public string TyJ_Code { get; set; }
    }
}
