//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_TableauEmploiJudiciaire1
    {
        public int TEJ_Id { get; set; }
        public int TEJ_Gra_Id { get; set; }
        public int TEJ_Gro_Id { get; set; }
        public int TEJ_TyJ_Id { get; set; }
        public int TEJ_Cla_Id { get; set; }
        public int TEJ_Emp_Id { get; set; }
        public string TEJ_Emp_Libelle { get; set; }
        public Nullable<System.DateTime> TEJ_DateEnregistrement { get; set; }
    }
}
