//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRHMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CompositionJuridiction
    {
        public int Coj_Id { get; set; }
        public string Coj_Emp_Code { get; set; }
        public string Coj_Jur_Code { get; set; }
        public Nullable<int> Coj_NombreRequis { get; set; }
        public Nullable<int> Coj_NombreReel { get; set; }
    }
}
